# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- task: Docker@2
  inputs:
    repository: 'idiotoflinux/dockersimh'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile-allsims'