version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t idiotoflinux/dockersimh:latest .

     # deploy the image
     - run: docker push idiotoflinux/dockersimh:latest
